version: "3"
services:
  database:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ${POSTGRES_LOCATION}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$${POSTGRES_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 50
  cache:
    image: redis:6

  directus:
    image: directus/directus:latest
    restart: always
    ports:
      - 8056:8055
    volumes:
      - ${DIRECTUS_LOCATION}:/directus/uploads
      - ${DIRECTUS_LOCATION}:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "${SECRET}"

      DB_CLIENT: "pg"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "5434"
      DB_DATABASE: "${POSTGRES_DB}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      # Make sure to set this in production
      PUBLIC_URL: "${PUBLIC_URL}"